[package]
name = "rword2vec"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.1"
rand = "0.9.2"
regex = "1.12.2"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
